name: CI-CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Repo çek
      uses: actions/checkout@v3

    - name: Docker login
      run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

    - name: Image build
      run: docker build -t sudekbr/myapp:latest .

    - name: Image push
      run: docker push sudekbr/myapp:latest